import { useEffect, useState } from 'react'
import { KeyRound, Save, ShieldCheck, Users } from 'lucide-react'
import { api } from '../api'

export function AccessPolicyConsole() {
  const [users, setUsers] = useState([]); const [policy, setPolicy] = useState(null); const [rules, setRules] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { Promise.all([api.adminUsers(), api.policy()]).then(([userData, policyData]) => { setUsers(userData.items || []); setPolicy(policyData); setRules(JSON.stringify(policyData.rules, null, 2)) }).catch((cause) => setError(cause.message)) }, [])
  const save = async () => { try { const next = await api.savePolicy({ rules: JSON.parse(rules) }); setPolicy(next); setMessage(`Policy v${next.version} activated`) } catch (cause) { setError(cause.message) } }
  return <div className="page policy-page"><section className="page-lead"><div><span className="eyebrow"><KeyRound size={14} /> Access & policy console</span><h2>Make the rules inspectable.</h2><p>Manage the seeded operating population and version the routing policy without rewriting in-flight requests.</p></div></section><section className="policy-grid"><article className="card-surface"><div className="section-title"><div><span className="eyebrow"><Users size={14} /> User registry</span><h3>{users.length} identities in the demo</h3></div></div><div className="user-list">{users.map((user) => <div className="user-row" key={user.user_id}><span className="avatar">{user.display_name.split(' ').map((word) => word[0]).slice(0, 2).join('')}</span><div><strong>{user.display_name}</strong><small>{user.email}</small></div><b>{user.role.replaceAll('_', ' ')}</b><em>{user.site_scopes.join(', ')}</em></div>)}</div></article><article className="card-surface policy-editor"><div className="section-title"><div><span className="eyebrow"><ShieldCheck size={14} /> Versioned routing</span><h3>Approval policy {policy ? `v${policy.version}` : ''}</h3></div><button className="primary-button" onClick={save}><Save size={15} />Save policy</button></div><textarea value={rules} onChange={(event) => setRules(event.target.value)} spellCheck="false" />{message && <p className="success-note">{message}</p>}{error && <p className="form-error">{error}</p>}</article></section></div>
}
