import { useMemo, useState } from 'react'
import { BellRing, CalendarClock, ChevronRight, Clock3, Filter, Sparkles } from 'lucide-react'
import { currency, severityLabel } from '../utils'

export function AlertsTimeline({ alerts, onSelectAnomaly }) {
  const [active, setActive] = useState('all')
  const visible = useMemo(() => active === 'all' ? alerts : alerts?.filter((alert) => alert.severity === active), [alerts, active])
  return <div className="page alerts-page"><section className="page-lead"><div><span className="eyebrow"><BellRing size={14} /> Forward-looking operations</span><h2>Act while the outcome is still optional.</h2><p>Alerts are ordered by modeled time to impact, not the time the source system happened to report a defect.</p></div><div className="timeline-forecast"><CalendarClock size={20} /><div><strong>Next 24 hours</strong><span>€{(alerts?.filter((item) => item.when.includes('h')) || []).reduce((total, item) => total + item.impact, 0).toLocaleString()} modeled exposure</span></div></div></section><section className="alert-filter"><span><Filter size={15} />Show</span>{['all', 'critical', 'high', 'medium', 'low'].map((item) => <button className={active === item ? 'active' : ''} key={item} onClick={() => setActive(item)}>{item === 'all' ? 'All alerts' : severityLabel(item)}</button>)}</section><section className="alert-timeline card-surface"><div className="timeline-title"><span className="eyebrow"><Sparkles size={14} /> Predicted deadline</span><h3>Operational runway</h3></div><div className="alerts-list">{visible?.map((alert, index) => <button className="alert-card" key={alert.id} onClick={() => onSelectAnomaly({ id: alert.id })}><div className={`alert-clock ${alert.severity}`}><Clock3 size={18} /><strong>{alert.when}</strong></div><div className="alert-copy"><span className={`severity-pill ${alert.severity}`}>{severityLabel(alert.severity)}</span><h3>{alert.title}</h3><p>{alert.detail}</p><small>Owner: {alert.owner}</small></div><div className="alert-impact"><span>Preventable exposure</span><strong>{currency(alert.impact)}</strong><ChevronRight size={18} /></div>{index !== visible.length - 1 && <i className="timeline-connector" />}</button>)}</div></section></div>
}

