import { useEffect, useMemo, useState } from 'react'
import { Download, FileClock, Search, ShieldCheck } from 'lucide-react'
import { api } from '../api'

export function AuditArchive() {
  const [events, setEvents] = useState([]); const [query, setQuery] = useState(''); const [site, setSite] = useState('all')
  useEffect(() => { api.request ? null : fetch('/api/audit').then((response) => response.json()).then((payload) => setEvents(payload.items || [])) }, [])
  const visible = useMemo(() => events.filter((event) => (site === 'all' || event.site_id === site) && `${event.event} ${event.actor} ${event.request_id || ''}`.toLowerCase().includes(query.toLowerCase())), [events, query, site])
  const download = () => { const body = ['timestamp,event,actor,role,site,request_id', ...visible.map((event) => [event.at, event.event, event.actor, event.role || '', event.site_id || '', event.request_id || ''].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([body], { type: 'text/csv' })); link.download = 'nexusai-audit-archive.csv'; link.click(); URL.revokeObjectURL(link.href) }
  return <div className="page archive-page"><section className="page-lead"><div><span className="eyebrow"><FileClock size={14} /> Immutable evidence</span><h2>The decision history stays put.</h2><p>Hash-linked events capture who decided, what they saw, and which snapshot moved through the workflow.</p></div><button className="soft-button" onClick={download}><Download size={15} />Export CSV</button></section><section className="toolbar card-surface"><label className="table-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter actor, event or request" /></label><select value={site} onChange={(event) => setSite(event.target.value)}><option value="all">All sites</option><option value="wolfsburg">Wolfsburg</option><option value="bratislava">Bratislava</option><option value="pune">Pune</option></select></section><section className="card-surface archive-list">{visible.map((event) => <article className="archive-event" key={event.id}><span className="archive-icon"><ShieldCheck size={16} /></span><div><strong>{event.event.replaceAll('_', ' ')}</strong><p>{event.actor} · {event.role || 'system'} · {event.site_id || 'global'}</p><small>{event.request_id || 'Dataset run event'} · {event.at}</small></div><code>{event.current_hash ? `${event.current_hash.slice(0, 12)}…` : 'legacy event'}</code></article>)}{!visible.length && <div className="empty-state"><FileClock size={23} /><h3>No audit events match</h3><p>Try another site or search term.</p></div>}</section></div>
}
